name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Dependencies
      env:
        NGINX_VERSION: 1.18.0
      run: |
        sudo apt-get update -y
        sudo apt-get install -y libssl-dev libcurl4-openssl-dev libhiredis-dev libmemcached-dev
        sudo apt-get install -y libjansson-dev libcjose-dev apache2-dev pkg-config
        cd /tmp        
        wget https://nginx.org/download/nginx-${NGINX_VERSION}.tar.gz
        tar zxvf nginx-${NGINX_VERSION}.tar.gz
        ln -s nginx-${NGINX_VERSION} nginx
        cd /tmp/nginx && ./configure --with-debug
        cd /tmp        
        git clone https://github.com/OpenIDC/liboauth2.git
        cd liboauth2
        ./autogen.sh
        ./configure --with-nginx=/tmp/nginx
        make
        sudo make install
    - name: Configure
      run: |
        ./autogen.sh
        ./configure --with-nginx=/tmp/nginx

    - name: Make
      run: make

    - name: Distcheck
      run: make distcheck DESTDIR="/tmp/ngx_openidc_module" DISTCHECK_CONFIGURE_FLAGS="--with-nginx=/tmp/nginx"
